#!/bin/sh

set -e

npm i && npm run build
bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D
bundle exec script/validate-html
gem build _config.gemspec
